[package]
name = "physics_sim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.35.2"

[dependencies.uuid]
version = "1.3.0"
features = [
    "v4",
    "fast-rng",
]
